pkg_name=cis-rhel-chef
pkg_origin=effortless-premium
pkg_version="0.2.7"
pkg_maintainer="Chef"
pkg_license=("Proprietary - All Rights Reserved")
pkg_scaffolding="chef/scaffolding-chef-infra"
scaffold_policy_name="Policyfile"
scaffold_policyfile_path="$PLAN_CONTEXT/../"
scaffold_chef_dk="chef/chef-dk/3.0.38"
