---
driver_config:
  name: ec2
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  region: us-west-2
  availability_zone: us-west-2a
  retryable_tries: 120
  tags: {
    Name:       "cis-rhel-kitchen",
    created-by: "test-kitchen"
  }

transport:
  ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
  username: 'ec2-user'

provisioner:
  name: chef_zero
  root_path: "/home/ec2-user/kitchen" # move from /tmp

verifier:
  name: inspec
  sudo: true

platforms:
  - name: rhel-7.4
    driver_config:
      image_id: ami-223f945a # RHEL 7.4 (HVM)
      instance_type: t2.medium
  - name: rhel-6
    driver:
      image-id: ami-7df0bd4d
      instance_type: t2.medium

suites:
  - name: aws-rhel7
    includes:
      - rhel-7.4
    verifier:
      inspec_tests:
        - test/integration/aws/rhel7/inspec # cis-rhel7-level1
    run_list:
      - recipe[cis-rhel::default]
    attributes:
      ssh-hardening:
        ssh:
          server:
            cipher: 'aes128-ctr,aes192-ctr,aes256-ctr'
      firewall:
        allow_ssh: true
  - name: aws-rhel6
    includes:
      - rhel-6
    verifier:
      inspec_tests:
        - test/integration/aws/rhel6/inspec # cis-rhel6-level1
    run_list:
      - recipe[cis-rhel::default]
    attributes:
      ssh-hardening:
        ssh:
          server:
            cipher: 'aes128-ctr,aes192-ctr,aes256-ctr'
      firewall:
        allow_ssh: true
