---
driver_config:
  name: ec2
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  region: us-west-2
  availability_zone: us-west-2a
  retryable_tries: 120
  tags: {
    Name:       "cis-rhel-kitchen",
    created-by: "test-kitchen"
  }

transport:
  ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
  username: 'ec2-user'

provisioner:
  name: chef_zero
  root_path: "/home/ec2-user/kitchen" # move from /tmp

verifier:
  name: inspec
  sudo: true

platforms:
# - name: rhel-6
#   verifier:
#     inspec_tests:
#       - TODO: Add path to compliance profile
  - name: rhel-7
    driver_config:
      image_id: ami-223f945a # RHEL 7.4 (HVM)
      instance_type: t2.micro
    verifier:
      inspec_tests:
        - test/integration/aws/inspec # cis-rhel7-level1

suites:
  - name: default
    run_list:
      - recipe[cis-rhel::default]
    attributes:
      ssh-hardening:
        ssh:
          server:
            cipher: 'aes128-ctr,aes192-ctr,aes256-ctr'
      firewall:
        allow_ssh: true
      rsyslog:
        config_files:
          mode: '0640'
        server_ip: 10.0.0.50
        custom_remote:
            - server: 10.0.0.45
              logs: auth.*,mail.*
              port: 555
              protocol: udp
            - server: 10.1.1.33
              logs: authpriv.*,cron.*,daemon.*
              port: 654
              protocol: tcp
              remote_template: RSYSLOG_SyslogProtocol23Format
