---
driver:
  name: ec2
  aws_ssh_key_id:
  region: eu-west-1
  availability_zone: a
  instance_type: t2.micro
  security_group_ids:
  subnet_id:
  retryable_tries: 120
  tags: {
    Name: "cis-rhel-kitchen",
    created-by: "test-kitchen"
  }

provisioner:
  name: chef_solo

platforms:
# - name: rhel-6
#   verifier:
#     inspec_tests:
#       - TODO: Add path to compliance profile
  - name: rhel-7
    verifier:
      inspec_tests:
        - ../compliance-profiles/src/inspec/supported/cis-rhel7-level1-server-v2.1.1

verifier:
  name: inspec
  sudo: true

transport:
  ssh_key:

suites:
  - name: default
    run_list:
      - recipe[cis-rhel::enable_sudo_no_tty]
